// <auto-generated />
namespace FormosBar.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class fiert : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(fiert));
        
        string IMigrationMetadata.Id
        {
            get { return "201912090729523_fiert"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
